### ISSUE TITLE
出现这样的错误，不知道该怎么修改了，求助！

### ISSUE THREAD

**Issue by lili1234567890** [murray-z/bert_multi_label_classification#3]
Traceback (most recent call last):
  File "F:/code/多标签分类/multi_label_classification-main/train.py", line 30, in <module>
    train_dataset = MultiClsDataSet(train_path, max_len=max_len, label2idx_path=label2idx_path)
  File "F:\code\多标签分类\multi_label_classification-main\data_helper.py", line 19, in __init__
    self.input_ids, self.token_type_ids, self.attention_mask, self.labels = self.encoder(data_path)
  File "F:\code\多标签分类\multi_label_classification-main\data_helper.py", line 39, in encoder
    is_split_into_words=False)
  File "C:\ProgramData\Anaconda3\envs\multi_label_classification-main\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'padding'

**Comment by murray-z** [comment]
你好，我因为没有数据，没有经过测试，我更新了一下代码和transformers的版本，你重新pull下代码再测试下呢

**Comment by lili1234567890** [comment]
出现新的错误如下：
Traceback (most recent call last):
  File "F:/code/多标签分类/multi_label_classification-main-n/train.py", line 30, in <module>
    train_dataset = MultiClsDataSet(train_path, max_len=max_len, label2idx_path=label2idx_path)
  File "F:\code\多标签分类\multi_label_classification-main-n\data_helper.py", line 15, in __init__
    self.input_ids, self.token_type_ids, self.attention_mask, self.labels = self.encoder(data_path)
  File "F:\code\多标签分类\multi_label_classification-main-n\data_helper.py", line 34, in encoder
    is_split_into_words=False)
TypeError: 'BertTokenizer' object is not callable

**Comment by murray-z** [comment]
我这边正常的啊，没有报错呢

**Comment by lili1234567890** [comment]
我今天查这个报错，可能是因为版本不一致问题，您这边方便提供一下您的运行环境环境吗，pytorchd 版本等！谢谢啦

**Comment by murray-z** [comment]
torch=1.10.0
transformers=4.18.0

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！
