### ISSUE TITLE
预测报错

### ISSUE THREAD

**Issue by fingerscross** [murray-z/bert_multi_label_classification#6]
请问你predict的时候有报错吗，我用你的例子训练预测，报错如下

Keyword arguments {'max_len': 128} not recognized.
Keyword arguments {'max_len': 128} not recognized.
Traceback (most recent call last):
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils_base.py", line 703, in convert_to_tensors
    tensor = as_tensor(value)
ValueError: expected sequence of length 3 at dim 1 (got 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Finaldesgin/multi_label_classification/predict.py", line 40, in <module>
    result = predict(texts)
  File "G:/Finaldesgin/multi_label_classification/predict.py", line 25, in predict
    outputs = tokenizer(texts, return_tensors="pt", max_len=max_len)
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils_base.py", line 2472, in __call__
    **kwargs,
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils_base.py", line 2663, in batch_encode_plus
    **kwargs,
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils.py", line 748, in _batch_encode_plus
    verbose=verbose,
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils.py", line 814, in _batch_prepare_for_model
    batch_outputs = BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils_base.py", line 208, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\transformers\tokenization_utils_base.py", line 720, in convert_to_tensors
    "Unable to create tensor, you should probably activate truncation and/or padding "
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

**Comment by murray-z** [comment]
更新了代码，你再pull下

**Comment by fingerscross** [comment]
没问题了，哪个class_num就是处理完数据，要预测的标签个数吧

**Comment by fingerscross** [comment]
十分感谢！
