### ISSUE TITLE
模型保存问题

### ISSUE THREAD

**Issue by fingerscross** [murray-z/bert_multi_label_classification#7]
20条数据测试是可以正常保存模型和预测的，但我试验200条数据时就会报错找不到模型保存的文件，如下，请问代码中有设置什么限制吗

Traceback (most recent call last):
  File "G:/Finaldesgin/multi_label_classification/train.py", line 124, in <module>
    train()
  File "G:/Finaldesgin/multi_label_classification/train.py", line 79, in train
    test_acc = test(save_model_path, test_path)
  File "G:/Finaldesgin/multi_label_classification/train.py", line 106, in test
    model.load_state_dict(torch.load(model_path))
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "G:\Anaconda3\envs\tensorflow\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'G:/Finaldesgin/multi_label_classification/model/multi_label_cls.pth'

**Comment by murray-z** [comment]
没有限制啊
